project:
  type: website
  preview:
    port: 7890

website:
  open-graph: true
  title: "Andrew Dinhobl"
  description: "Andrew's personal blog"
  favicon: favicon.ico
  draft-mode: unlinked
  navbar:
    left:
      - text: Posts
        file: index.qmd
      - projects.qmd
    right:
      - icon: twitter
        href: https://x.com/adinhobl
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-dinhobl/
      - icon: github
        href: https://github.com/adinhobl
  repo-url: https://github.com/adinhobl/adinhobl.github.io
  twitter-card:
    creator: "@adinhobl"
format:
  html:
    theme: lux
    css: styles.css
    toc: true
# editor:
#   render-on-save: true # https://quarto.org/docs/tools/vscode.html#render-on-save


# TODO set up giscus https://giscus.app/