project:
  type: website

website:
  open-graph: true
  title: "Andrew Dinhobl"
  description: "Andrew's personal blog"
  navbar:
    left:
      - text: Posts
        file: index.qmd
      - projects.qmd
      - notes/index.qmd
    right:
      - icon: twitter
        href: https://x.com/adinhobl
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-dinhobl/
      - icon: github
        href: https://github.com/adinhobl
  repo-url: https://github.com/adinhobl/adinhobl.github.io
format:
  html:
    theme: lux
    mainfont: Roboto
    css: styles.css
    toc: true



# TODO set up giscus https://giscus.app/